name: Build

on:
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.1"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest

    - name: Setup github config
      run: |
        git config --global user.email "<>"
        git config --global user.name "github-actions[bot]"

    - name: Build the site
      run: |
        pip install pygbag
        pip install -r requirements.txt

        name=${PWD##*/}
        cd ..
        pygbag --build $name
        cd $name

    - name: Commit changes
      run: |
        # -f to override .gitignore
        git switch gh-pages
        git add -f build/web
        git commit -m "New version"
        git push origin master
